
clear all
close all
root='...'

for EXPT=1:3
    for effects=1:7
        samples{EXPT}{effects}=load([root num2str(EXPT) '_effects_' num2str(effects)]);
    end
end

additionalcondname={'Setsize','Mask','Sequence Position'};

%% Plot Precision
for EXPT=1:3
    figure
    errorBarPlot([samples{EXPT}{4}.samples(:,1),...
        samples{EXPT}{2}.samples(:,1),...
        samples{EXPT}{3}.samples(:,1),...
        samples{EXPT}{5}.samples(:,1),...
        samples{EXPT}{1}.samples(:,1),...
        samples{EXPT}{6}.samples(:,1),...
        samples{EXPT}{7}.samples(:,1)])
    xticklabels({'No effects', 'Probe Type Only', 'Additional Factor', 'Both Factors',...
        'Both Factors and Interaction', 'Probe Type, Precision Only',...
        'Probe Type, Target Response Only'})
    xtickangle(45)
    xlim([0.5 7.5])
    ylim([11 17])
    title(['Experiment ' num2str(EXPT)])
    legend({'Precision'})
    set(gca,'FontSize',16)

end


%% Plot Probabilities


for EXPT=1:3
    figure
    hold on 

    % Target Response
    errorBarPlot([samples{EXPT}{4}.samples(:,3).*samples{EXPT}{4}.samples(:,2),...
        samples{EXPT}{2}.samples(:,3).*samples{EXPT}{2}.samples(:,2),...
        samples{EXPT}{3}.samples(:,3).*samples{EXPT}{3}.samples(:,2),...
        samples{EXPT}{5}.samples(:,3).*samples{EXPT}{5}.samples(:,2),...
        samples{EXPT}{1}.samples(:,3).*samples{EXPT}{1}.samples(:,2),...
        samples{EXPT}{6}.samples(:,3).*samples{EXPT}{6}.samples(:,2),...
        samples{EXPT}{7}.samples(:,3).*samples{EXPT}{7}.samples(:,2)])

    % Non-Target Response
    errorBarPlot([(1-samples{EXPT}{4}.samples(:,3)).*samples{EXPT}{4}.samples(:,2),...
        (1-samples{EXPT}{2}.samples(:,3)).*samples{EXPT}{2}.samples(:,2),...
        (1-samples{EXPT}{3}.samples(:,3)).*samples{EXPT}{3}.samples(:,2),...
        (1-samples{EXPT}{5}.samples(:,3)).*samples{EXPT}{5}.samples(:,2),...
        (1-samples{EXPT}{1}.samples(:,3)).*samples{EXPT}{1}.samples(:,2),...
        (1-samples{EXPT}{6}.samples(:,3)).*samples{EXPT}{6}.samples(:,2),...
        (1-samples{EXPT}{7}.samples(:,3)).*samples{EXPT}{7}.samples(:,2)])

    % Uniform Response    
    errorBarPlot([(1-samples{EXPT}{4}.samples(:,2)),...
        (1-samples{EXPT}{2}.samples(:,2)),...
        (1-samples{EXPT}{3}.samples(:,2)),...
        (1-samples{EXPT}{5}.samples(:,2)),...
        (1-samples{EXPT}{1}.samples(:,2)),...
        (1-samples{EXPT}{6}.samples(:,2)),...
        (1-samples{EXPT}{7}.samples(:,2))])

    
    hold off

    xticklabels({'No effects', 'Probe Type Only', 'Additional Factor', 'Both Factors',...
        'Both Factors and Interaction', 'Probe Type, Precision Only',...
        'Probe Type, Target Response Only'})
    xtickangle(45)
    set(gca,'FontSize',16)


    xlim([0.5 7.5])
    ylim([0 1])
    
    legend({'Target Response','Non-Target Response','Uniform Response'})

    title(['Experiment ' num2str(EXPT)])
    
end
